/**
 * Emit the `.github/workflows/seo-aeo.yml` cron. GitHub Actions cron can't
 * express "every other week", so biweekly runs weekly + an ISO-week parity
 * gate that skips odd weeks.
 */
import type { Cadence } from "../engine/types.js";

export const WEEKLY_CRON = "0 14 * * 1"; // Mondays 14:00 UTC

export function cronFor(_frequency: Cadence["frequency"]): string {
  // Both cadences fire weekly on the schedule; biweekly is gated in-job.
  return WEEKLY_CRON;
}

export function workflowYaml(cadence: Cadence): string {
  const cron = cadence.cron || WEEKLY_CRON;
  const biweekly = cadence.frequency === "biweekly";

  const gate = biweekly
    ? `      - name: Biweekly gate (skip odd ISO weeks)
        if: github.event_name == 'schedule'
        run: |
          WEEK=$(date -u +%V)
          if [ $((10#$WEEK % 2)) -ne 0 ]; then
            echo "Odd ISO week ($WEEK) — skipping this run (biweekly cadence)."
            echo "SEO_AEO_SKIP=1" >> "$GITHUB_ENV"
          fi
`
    : "";

  const runIf = biweekly ? "\n        if: env.SEO_AEO_SKIP != '1'" : "";

  return `# Generated by \`npx seo-aeo init\`. Cadence: ${cadence.frequency}.
# Requires repo secrets: ANTHROPIC_API_KEY (and GEMINI_API_KEY if images are on).
name: seo-aeo

on:
  schedule:
    - cron: "${cron}"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  write-article:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
${gate}      - name: Generate and open PR${runIf}
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: \${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "seo-aeo[bot]"
          git config user.email "seo-aeo@users.noreply.github.com"
          npx -y @elinewman/seo-aeo run
`;
}
