/**
 * Stage 8: publish. Filesystem + git side-effects. Writes the MDX draft,
 * then (unless dry-run) branches, commits, pushes, and opens a PR via
 * `gh`. Degrades gracefully: no remote → commit only; no `gh` → push only.
 */
import { mkdir, writeFile, rename, unlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

import { execa } from "execa";

import type { Article, ProjectConfig } from "../types.js";
import { renderMdx } from "../mdx.js";
import { log } from "../log.js";

export interface PublishResult {
  draftPath: string;
  branch?: string;
  prUrl?: string;
  committed: boolean;
}

function draftsDir(root: string, project: ProjectConfig): string {
  return path.join(root, project.layout.draftsPath);
}

function postsDir(root: string, project: ProjectConfig): string {
  return path.join(root, project.layout.postsPath);
}

/** Render + write the MDX draft. Returns the absolute path. */
export async function writeDraft(
  root: string,
  article: Article,
  project: ProjectConfig,
): Promise<string> {
  const dir = draftsDir(root, project);
  await mkdir(dir, { recursive: true });
  const file = path.join(dir, `${article.slug}.mdx`);
  await writeFile(file, renderMdx(article), "utf8");
  log.ok(`wrote draft → ${path.relative(root, file)}`);
  return file;
}

async function git(
  root: string,
  args: string[],
  opts: { check?: boolean } = {},
): Promise<{ code: number; stdout: string; stderr: string }> {
  const res = await execa("git", ["-C", root, ...args], { reject: false });
  if (opts.check && res.exitCode !== 0) {
    throw new Error(`git ${args.join(" ")} failed: ${res.stderr}`);
  }
  return { code: res.exitCode ?? 1, stdout: res.stdout, stderr: res.stderr };
}

async function hasRemote(root: string): Promise<boolean> {
  const res = await git(root, ["remote"]);
  return res.code === 0 && res.stdout.trim().length > 0;
}

async function hasGh(): Promise<boolean> {
  const res = await execa("gh", ["--version"], { reject: false });
  return (res.exitCode ?? 1) === 0;
}

/**
 * Branch, commit the draft, push, and open a PR. Best-effort — returns
 * what it managed to do. In CI, set GITHUB_TOKEN/GH_TOKEN for `gh`.
 */
export async function openDraftPr(
  root: string,
  article: Article,
  draftPath: string,
  _project: ProjectConfig,
): Promise<PublishResult> {
  const result: PublishResult = { draftPath, committed: false };

  if (!existsSync(path.join(root, ".git"))) {
    log.warn("not a git repo — wrote the draft but skipped PR.");
    return result;
  }

  const branch = `seo-aeo/${article.slug}`;
  result.branch = branch;
  await git(root, ["checkout", "-B", branch], { check: true });
  await git(root, ["add", "--", path.relative(root, draftPath)], { check: true });

  const title = `Add article: ${article.frontmatter.title}`;
  const commit = await git(root, ["commit", "-m", title]);
  if (commit.code !== 0) {
    if (/nothing to commit/i.test(commit.stdout + commit.stderr)) {
      log.warn("nothing to commit.");
      return result;
    }
    throw new Error(`git commit failed: ${commit.stderr}`);
  }
  result.committed = true;
  log.ok(`committed on ${branch}`);

  if (!(await hasRemote(root))) {
    log.warn("no git remote — committed locally, skipped push/PR.");
    return result;
  }
  await git(root, ["push", "-u", "origin", branch, "--force-with-lease"], {
    check: true,
  });

  if (!(await hasGh())) {
    log.warn("`gh` CLI not found — pushed the branch; open the PR manually.");
    return result;
  }

  const wc = article.wordCount;
  const body = [
    `Auto-generated by \`seo-aeo\`.`,
    "",
    `**Target keyword:** ${article.frontmatter.keywords[0] ?? "—"}`,
    `**Word count:** ${wc}`,
    `**Images:** ${article.images.length}`,
    "",
    `Review the draft in \`${path.relative(root, draftPath)}\`, then merge to publish.`,
  ].join("\n");

  const pr = await execa(
    "gh",
    ["pr", "create", "--title", title, "--body", body, "--head", branch],
    { cwd: root, reject: false },
  );
  if ((pr.exitCode ?? 1) === 0) {
    result.prUrl = pr.stdout.trim();
    log.ok(`opened PR → ${result.prUrl}`);
  } else {
    log.warn(`gh pr create failed: ${pr.stderr.slice(0, 160)}`);
  }
  return result;
}

/** Move drafts/<slug>.mdx → posts/<slug>.mdx. Won't overwrite a post. */
export async function promote(
  root: string,
  slug: string,
  project: ProjectConfig,
): Promise<string> {
  const src = path.join(draftsDir(root, project), `${slug}.mdx`);
  if (!existsSync(src)) throw new Error(`No draft to promote at ${src}`);
  const dstDir = postsDir(root, project);
  await mkdir(dstDir, { recursive: true });
  const dst = path.join(dstDir, `${slug}.mdx`);
  if (existsSync(dst))
    throw new Error(`Refusing to overwrite already-published post at ${dst}.`);
  await rename(src, dst);
  return dst;
}

/** Delete a draft (reject flow). */
export async function deleteDraft(
  root: string,
  slug: string,
  project: ProjectConfig,
): Promise<string> {
  const file = path.join(draftsDir(root, project), `${slug}.mdx`);
  if (!existsSync(file)) throw new Error(`No draft to delete at ${file}`);
  await unlink(file);
  return file;
}
